// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/Vigneshwartt/golang-rte-task/common/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Vigneshwartt/golang-rte-task/pkg/models"
)

// IAdminRepo is an autogenerated mock type for the IAdminRepo type
type IAdminRepo struct {
	mock.Mock
}

// CreateJobPost provides a mock function with given fields: jobCreation
func (_m *IAdminRepo) CreateJobPost(jobCreation *models.JobCreation) *dto.ErrorResponse {
	ret := _m.Called(jobCreation)

	if len(ret) == 0 {
		panic("no return value specified for CreateJobPost")
	}

	var r0 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func(*models.JobCreation) *dto.ErrorResponse); ok {
		r0 = rf(jobCreation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ErrorResponse)
		}
	}

	return r0
}

// DeleteJobPost provides a mock function with no fields
func (_m *IAdminRepo) DeleteJobPost() *dto.ErrorResponse {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobPost")
	}

	var r0 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func() *dto.ErrorResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ErrorResponse)
		}
	}

	return r0
}

// GetApplicantAndJobDetails provides a mock function with given fields: jobDetails
func (_m *IAdminRepo) GetApplicantAndJobDetails(jobDetails map[string]interface{}) ([]models.UserJobDetails, *dto.ErrorResponse, int64) {
	ret := _m.Called(jobDetails)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicantAndJobDetails")
	}

	var r0 []models.UserJobDetails
	var r1 *dto.ErrorResponse
	var r2 int64
	if rf, ok := ret.Get(0).(func(map[string]interface{}) ([]models.UserJobDetails, *dto.ErrorResponse, int64)); ok {
		return rf(jobDetails)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []models.UserJobDetails); ok {
		r0 = rf(jobDetails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserJobDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) *dto.ErrorResponse); ok {
		r1 = rf(jobDetails)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.ErrorResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(map[string]interface{}) int64); ok {
		r2 = rf(jobDetails)
	} else {
		r2 = ret.Get(2).(int64)
	}

	return r0, r1, r2
}

// GetJobsAppliedByUser provides a mock function with given fields: userIDJobs
func (_m *IAdminRepo) GetJobsAppliedByUser(userIDJobs map[string]interface{}) ([]models.UserJobDetails, *dto.ErrorResponse, int64) {
	ret := _m.Called(userIDJobs)

	if len(ret) == 0 {
		panic("no return value specified for GetJobsAppliedByUser")
	}

	var r0 []models.UserJobDetails
	var r1 *dto.ErrorResponse
	var r2 int64
	if rf, ok := ret.Get(0).(func(map[string]interface{}) ([]models.UserJobDetails, *dto.ErrorResponse, int64)); ok {
		return rf(userIDJobs)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []models.UserJobDetails); ok {
		r0 = rf(userIDJobs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserJobDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) *dto.ErrorResponse); ok {
		r1 = rf(userIDJobs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.ErrorResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(map[string]interface{}) int64); ok {
		r2 = rf(userIDJobs)
	} else {
		r2 = ret.Get(2).(int64)
	}

	return r0, r1, r2
}

// GetJobsCreated provides a mock function with given fields: createdPosts
func (_m *IAdminRepo) GetJobsCreated(createdPosts map[string]interface{}) ([]models.JobCreation, *dto.ErrorResponse, int64) {
	ret := _m.Called(createdPosts)

	if len(ret) == 0 {
		panic("no return value specified for GetJobsCreated")
	}

	var r0 []models.JobCreation
	var r1 *dto.ErrorResponse
	var r2 int64
	if rf, ok := ret.Get(0).(func(map[string]interface{}) ([]models.JobCreation, *dto.ErrorResponse, int64)); ok {
		return rf(createdPosts)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []models.JobCreation); ok {
		r0 = rf(createdPosts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobCreation)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) *dto.ErrorResponse); ok {
		r1 = rf(createdPosts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.ErrorResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(map[string]interface{}) int64); ok {
		r2 = rf(createdPosts)
	} else {
		r2 = ret.Get(2).(int64)
	}

	return r0, r1, r2
}

// UpdateJobPost provides a mock function with given fields: jobData, jobID, userID
func (_m *IAdminRepo) UpdateJobPost(jobData *models.JobCreation, jobID int, userID int) *dto.ErrorResponse {
	ret := _m.Called(jobData, jobID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobPost")
	}

	var r0 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func(*models.JobCreation, int, int) *dto.ErrorResponse); ok {
		r0 = rf(jobData, jobID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ErrorResponse)
		}
	}

	return r0
}

// NewIAdminRepo creates a new instance of IAdminRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdminRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdminRepo {
	mock := &IAdminRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
