// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/Vigneshwartt/golang-rte-task/common/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Vigneshwartt/golang-rte-task/pkg/models"
)

// IAuthRepo is an autogenerated mock type for the IAuthRepo type
type IAuthRepo struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: userDetails
func (_m *IAuthRepo) CreateUser(userDetails *models.UserDetails) *dto.ErrorResponse {
	ret := _m.Called(userDetails)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func(*models.UserDetails) *dto.ErrorResponse); ok {
		r0 = rf(userDetails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ErrorResponse)
		}
	}

	return r0
}

// GetUserDetail provides a mock function with given fields: userDetails
func (_m *IAuthRepo) GetUserDetail(userDetails *models.UserDetails) (*models.UserDetails, *dto.ErrorResponse) {
	ret := _m.Called(userDetails)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDetail")
	}

	var r0 *models.UserDetails
	var r1 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func(*models.UserDetails) (*models.UserDetails, *dto.ErrorResponse)); ok {
		return rf(userDetails)
	}
	if rf, ok := ret.Get(0).(func(*models.UserDetails) *models.UserDetails); ok {
		r0 = rf(userDetails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.UserDetails) *dto.ErrorResponse); ok {
		r1 = rf(userDetails)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.ErrorResponse)
		}
	}

	return r0, r1
}

// GetUserMail provides a mock function with given fields: userEmail
func (_m *IAuthRepo) GetUserMail(userEmail string) *dto.ErrorResponse {
	ret := _m.Called(userEmail)

	if len(ret) == 0 {
		panic("no return value specified for GetUserMail")
	}

	var r0 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func(string) *dto.ErrorResponse); ok {
		r0 = rf(userEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ErrorResponse)
		}
	}

	return r0
}

// GetUserPhoneNumber provides a mock function with given fields: userPhoneNumber
func (_m *IAuthRepo) GetUserPhoneNumber(userPhoneNumber string) *dto.ErrorResponse {
	ret := _m.Called(userPhoneNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPhoneNumber")
	}

	var r0 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func(string) *dto.ErrorResponse); ok {
		r0 = rf(userPhoneNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ErrorResponse)
		}
	}

	return r0
}

// NewIAuthRepo creates a new instance of IAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthRepo {
	mock := &IAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
