// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/Vigneshwartt/golang-rte-task/common/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Vigneshwartt/golang-rte-task/pkg/models"
)

// IUserRepo is an autogenerated mock type for the IUserRepo type
type IUserRepo struct {
	mock.Mock
}

// CreateApplication provides a mock function with given fields: userJobDetails
func (_m *IUserRepo) CreateApplication(userJobDetails *models.UserJobDetails) *dto.ErrorResponse {
	ret := _m.Called(userJobDetails)

	if len(ret) == 0 {
		panic("no return value specified for CreateApplication")
	}

	var r0 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func(*models.UserJobDetails) *dto.ErrorResponse); ok {
		r0 = rf(userJobDetails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ErrorResponse)
		}
	}

	return r0
}

// GetAllJobPosts provides a mock function with given fields: searchJobs
func (_m *IUserRepo) GetAllJobPosts(searchJobs map[string]interface{}) ([]models.JobCreation, *dto.ErrorResponse, int64) {
	ret := _m.Called(searchJobs)

	if len(ret) == 0 {
		panic("no return value specified for GetAllJobPosts")
	}

	var r0 []models.JobCreation
	var r1 *dto.ErrorResponse
	var r2 int64
	if rf, ok := ret.Get(0).(func(map[string]interface{}) ([]models.JobCreation, *dto.ErrorResponse, int64)); ok {
		return rf(searchJobs)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []models.JobCreation); ok {
		r0 = rf(searchJobs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobCreation)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) *dto.ErrorResponse); ok {
		r1 = rf(searchJobs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.ErrorResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(map[string]interface{}) int64); ok {
		r2 = rf(searchJobs)
	} else {
		r2 = ret.Get(2).(int64)
	}

	return r0, r1, r2
}

// GetUserAppliedJobs provides a mock function with given fields: userJobs
func (_m *IUserRepo) GetUserAppliedJobs(userJobs map[string]interface{}) ([]models.UserJobDetails, *dto.ErrorResponse, int64) {
	ret := _m.Called(userJobs)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAppliedJobs")
	}

	var r0 []models.UserJobDetails
	var r1 *dto.ErrorResponse
	var r2 int64
	if rf, ok := ret.Get(0).(func(map[string]interface{}) ([]models.UserJobDetails, *dto.ErrorResponse, int64)); ok {
		return rf(userJobs)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) []models.UserJobDetails); ok {
		r0 = rf(userJobs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserJobDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) *dto.ErrorResponse); ok {
		r1 = rf(userJobs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.ErrorResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(map[string]interface{}) int64); ok {
		r2 = rf(userJobs)
	} else {
		r2 = ret.Get(2).(int64)
	}

	return r0, r1, r2
}

// GetUserByID provides a mock function with given fields: userJobDetails
func (_m *IUserRepo) GetUserByID(userJobDetails *models.UserJobDetails) *dto.ErrorResponse {
	ret := _m.Called(userJobDetails)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *dto.ErrorResponse
	if rf, ok := ret.Get(0).(func(*models.UserJobDetails) *dto.ErrorResponse); ok {
		r0 = rf(userJobDetails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ErrorResponse)
		}
	}

	return r0
}

// NewIUserRepo creates a new instance of IUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserRepo {
	mock := &IUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
